### ISSUE TITLE
Test all application at Websoft9 console

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/docker-library#431]
Need to:

1. Test all application at Websoft9 console
标准：安装无需任何障碍，一旦有障碍即记录为 Issue[文字描述问题+截图]

测试服务器：http://121.41.131.230:9000   , 账号 ：root/websoft9@

2. 如果是安装的Latest 版本，请记录版本号：应用的界面获取或docker inspect 获取

以下是过程记录范例

- [ ] appname 1 bug, latest version is 3.3.2, #323
- [ ] appname2  success, latest version is 3.3.2

App lists below:  

- [x] activemq success, version is 5.18.2-jre17-rockylinux8
- [x] akaunting bug, #447  fixed
- [x] akeneo bug, #451
- [x] alfresco bug, #527
- [x] ansible bug, version is 2.9.0, #455
- [x] apache bug, #457
- [x] apex bug, versin is 22.1.0, #475
- [x] aitable bug, #476, #514
- [x] appflowy bug, #528
- [x] appsmith bug, #479
- [x] arangodb success, latest version is 3.11.5
- [x] awx bug, version is 22.5.0, #482
- [x] budibase bug, latest version is 2.13.31, #508
- [x] caddy bug, #462
- [x] chat2db bug, version is 2.0.6, #464
- [x] chatgptnextweb bug, #467
- [x] clamav bug, version is unstable, ##484
- [x] cloudbeaver bug, #486
- [x] codeserver bug, latest version is 4.19.1, #494
- [x] couchdb bug, #492
- [x] dgraph bug, #496
- [x] directus bug, #526
- [x] discourse bug, latest version is 3.1.3, #501
- [x] discuz success, version is v3.4.0
- [x] discuzq error, version is v3.0, #534
- [x] dolibarr success, version is 18.0.1
- [x] drupal success, latest version is 10.1.6
- [ ] elastic
- [x] elasticsearch bug,  version is 8.6.0, #515
- [x] erpnext bug,  version is v14, #516
- [x] espocrm bug, latest version is 8.0.5, #517
- [x] excalidraw bug, #518
- [x] focalboard bug, #520
- [x] ghost success, latest version is 5.75.0
- [x] gitea success, latest version is 1.21.1
- [x] gitlab success, latest version is 16.6.1
- [x] gogs success, latest version is 0.14.0+dev
- [x] grafana bug, #525
- [x] graylog bug, version is 5.1, #524
- [x] haproxy bug, version is 2.8, #443
- [x] homeassistant, #502
- [x] huginn bug, #504
- [x] humhub bug,  #444
- [x] influxdb bug,  #445
- [x] jenkins bug, #446
- [x] joomla success, latest version is 5.0.1
- [x] jupyterhub, #506
- [x] kafka bug, latest version is 3.6.0, #450
- [ ] kasmweb
- [x] knowage bug, version is 7.4.18 #448
- [x] kodbox bug, #452
- [x] kong bug, #454
- [x] magento bug, latest version is 2.4.6, #458
- [x] mariadb success, version is 11.2.2
- [x] matomo bug, version is 4.15.1, #463
- [x] mattermost bug, #465
- [x] mautic bug, #469
- [x] mediawiki bug, #470
- [x] memcached bug, latest version is 1.6.22, #472
- [x] metabase success, latest version is 0.47.9
- [x] minio success
- [x] mongocompass bug, #477
- [ ] mongodb
- [x] moodle bug, latest version is 4.3, #480
- [x] mysql success, version is 8.1.0
- [x] n8n bug, #483
- [x] neo4j bug, #488
- [x] netdata bug, #487
- [x] nextcloud success
- [x] nextterminal bug, #510
- [x] nocobase bug, #489
- [x] nocodb bug, #490
- [x] nopcommerce bug, #491
- [x] odoo success, latest version is 17.0
- [ ] onlyoffice
- [x] onlyofficedocs bug, latest version is 7.5.1-23, #497
- [x] opencart bug, #498
- [ ] opensearch
- [x] oracle  bug,  #442
- [x] owncloud  success, latest version is 10.13.3
- [x] pgadmin  success, latest version is 8.0
- [x] phpmyadmin  success, latest version is 5.2.1
- [x] plausible  bug,#449
- [x] postgresql  bug,latest version is 16.1,#495
- [x] prestashop  bug, latest version is VERSION, #453
- [x] pydio bug,latest version is 2.20.2, #456
- [x] rabbitmq  bug,#460
- [x] redis  bug,#461
- [x] redisinsight  success
- [x] redmine bug,latest version is 5.0,#466
- [x] redpandaconsole  bug,#468
- [x] rethinkdb  bug,#471
- [x] rocketchat  bug,#473
- [x] scratch  bug,#474
- [x] seafile  bug, latest version is 11.0.2 ,#478
- [x] sqlserver  bug,#481
- [x] srs  bug,#485
- [ ] sscms
- [x] strapi bug,#493
- [x] suitecrm success, latest version is 8.4.2
- [x] superset  bug,#499
- [x] teleport  bug,#500
- [x] tensorflow  bug,#503
- [ ] theia
- [x] thingsboard  bug,#507
- [x] traefik  bug,#509
- [x] typesense  bug,#511
- [x] typo3  success, latest version is 12.4.8
- [ ] umami
- [x] vault  bug,latest version is 1.13.3, #513
- [x] vtiger  success , latest version is 7.4.0
- [x] webmin  success, latest version is 1.998
- [x] wordpress  success,latest version is 6.4.1
- [x] zabbix  bug,#519
- [x] zammad  bug,#521
- [x] zentao  success,latest version is 18.9
